# Generated by Django 2.2.8 on 2021-12-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True, max_length=100)),
                ('tipo_progrmador', models.CharField(choices=[('JUNIOR', 'JUNIOR'), ('MID SENIOR', 'MID SENIOR'), ('SENIOR', 'SENIOR')], default='JUNIOR', max_length=50, verbose_name='Tipo de Programador')),
            ],
        ),
    ]
