# Generated by Django 2.2.8 on 2021-12-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programador',
            name='tipo_progrmador',
        ),
    ]
